/*
=========================================================
BIASHNET COMPLETION CODE SERVICE
=========================================================

PURPOSE
---------------------------------------------------------

Controls the unique buyer completion code used to confirm
successful delivery.

FLOW:

PAYMENT SUCCESSFUL
        ↓
FUNDS HELD
        ↓
BUYER RECEIVES COMPLETION CODE
        ↓
SELLER DELIVERS PRODUCT
        ↓
SELLER ENTERS CODE
        ↓
BACKEND VERIFIES CODE
        ↓
ORDER = COMPLETED
        ↓
SETTLEMENT SERVICE
        ↓
SELLER WALLET CREDITED

IMPORTANT:

- Buyer receives the plain code.
- Database stores ONLY the hash.
- Seller never receives the code automatically.
- Code can only be used once.
- Wrong attempts are tracked.
- Completed orders cannot be completed again.
- Settlement happens only after successful verification.
=========================================================
*/

const crypto = require("crypto");

const {
    db,
    FieldValue,
} = require("../config/firebase");

const {
    COLLECTIONS,
} = require("../config/collections");

const {
    PAYMENT_STATUS,
    ORDER_STATUS,
    SELLER_PAYMENT_STATUS,
} = require("../config/paymentConstants");

const {
    generateCompletionCode,
} = require("../utils/codeGenerator");

const {
    settleMarketplaceOrder,
} = require("./settlementService");


/*
=========================================================
CONFIGURATION
=========================================================
*/

const CODE_LENGTH = 6;

const MAX_VERIFICATION_ATTEMPTS = 5;


/*
=========================================================
HASH COMPLETION CODE
=========================================================

The plain code should NEVER be stored in Firestore.



=========================================================
*/

function hashCompletionCode(code) {

    return crypto
        .createHash("sha256")
        .update(
            String(code)
                .trim()
                .toUpperCase()
        )
        .digest("hex");

}


/*
=========================================================
NORMALIZE CODE
=========================================================
*/

function normalizeCode(code) {

    return String(code || "")
        .trim()
        .toUpperCase();

}


/*
=========================================================
VALIDATE CODE FORMAT
=========================================================
*/

function validateCodeFormat(code) {

    const normalized =
        normalizeCode(code);


    if (!normalized) {

        throw new Error(
            "Completion code is required."
        );

    }


    /*
    Current completion codes generated by
    generateCompletionCode() are 6 characters.
    */

    if (
        normalized.length !== CODE_LENGTH
    ) {

        throw new Error(
            "Invalid completion code."
        );

    }


    /*
    Our generator currently creates hexadecimal
    characters, therefore:

    0-9
    A-F
    */

    if (
        !/^[A-F0-9]{6}$/.test(
            normalized
        )
    ) {

        throw new Error(
            "Invalid completion code format."
        );

    }


    return normalized;

}


/*
=========================================================
GET COMPLETION CODE DOCUMENT
=========================================================

Stored inside the order itself:

marketplaceOrders/{orderId}

Fields:

completionCodeHash
completionCodeCreatedAt
completionCodeUsed
completionCodeUsedAt
completionCodeAttempts
=========================================================
*/

async function getOrder(
    orderId
) {

    const orderRef =
        db
            .collection(
                COLLECTIONS.ORDERS
            )
            .doc(orderId);


    const snap =
        await orderRef.get();


    if (!snap.exists) {

        throw new Error(
            "Marketplace order not found."
        );

    }


    return {
        ref: orderRef,
        data: snap.data(),
    };

}


/*
=========================================================
GENERATE COMPLETION CODE
=========================================================

Called after successful payment.

ONLY THE BUYER SHOULD RECEIVE THE PLAIN CODE.

The backend stores:

completionCodeHash

NOT:

completionCode
=========================================================
*/

async function generateOrderCompletionCode({

    orderId,

    buyerId,

}) {

    console.log(
        "=========================================="
    );

    console.log(
        "🔐 GENERATING ORDER COMPLETION CODE"
    );

    console.log(
        "Order:",
        orderId
    );

    console.log(
        "Buyer:",
        buyerId
    );

    console.log(
        "=========================================="
    );


    /*
    =======================================================
    VALIDATION
    =======================================================
    */

    if (!orderId) {

        throw new Error(
            "Order ID is required."
        );

    }


    if (!buyerId) {

        throw new Error(
            "Buyer ID is required."
        );

    }


    /*
    =======================================================
    GET ORDER
    =======================================================
    */

    const {
        ref: orderRef,
        data: order,
    } = await getOrder(
        orderId
    );


    /*
    =======================================================
    VERIFY BUYER
    =======================================================
    */

    if (
        order.buyerId !== buyerId
    ) {

        throw new Error(
            "You are not authorized to generate this completion code."
        );

    }


    /*
    =======================================================
    VERIFY PAYMENT
    =======================================================
    */

    if (
        order.paymentStatus !==
        PAYMENT_STATUS.COMPLETED
    ) {

        throw new Error(
            "Completion code can only be generated after successful payment."
        );

    }


    /*
    =======================================================
    DO NOT GENERATE AGAIN
    =======================================================
    */

    if (
        order.completionCodeHash
    ) {

        /*
        Security rule:

        We cannot return the old code because only
        the hash is stored.

        The frontend should have received the code
        when it was originally generated.
        */

        throw new Error(
            "A completion code has already been generated for this order."
        );

    }


    /*
    =======================================================
    GENERATE CODE
    =======================================================
    */

    const code =
        generateCompletionCode();


    const normalizedCode =
        normalizeCode(code);


    const codeHash =
        hashCompletionCode(
            normalizedCode
        );


    const now =
        new Date();


    /*
    =======================================================
    SAVE HASH
    =======================================================
    */

    await orderRef.update({

        completionCodeHash:
            codeHash,

        completionCodeCreatedAt:
            now,

        completionCodeUsed:
            false,

        completionCodeAttempts:
            0,

        completionCodeStatus:
            "ACTIVE",

        updatedAt:
            now,

    });


    console.log(
        "✅ Completion code generated."
    );


    /*
    =======================================================
    IMPORTANT

    Return plain code ONLY HERE.

    Do not save this value to Firestore.
    =======================================================
    */

    return {

        success: true,

        orderId,

        code:
            normalizedCode,

        message:
            "Completion code generated. Keep this code safe and share it with the seller only after successful delivery.",

    };

}


/*
=========================================================
VERIFY COMPLETION CODE
=========================================================

SELLER submits:

orderId
sellerId
code

Backend:

1. Gets order
2. Verifies seller
3. Verifies payment
4. Checks code status
5. Checks attempt limit
6. Hashes submitted code
7. Compares hashes
8. Marks code used
9. Marks order completed
10. Calls settlement service

=========================================================
*/

async function verifyCompletionCode({

    orderId,

    sellerId,

    code,

}) {

    console.log(
        "=========================================="
    );

    console.log(
        "🔐 VERIFYING ORDER COMPLETION CODE"
    );

    console.log(
        "Order:",
        orderId
    );

    console.log(
        "Seller:",
        sellerId
    );

    console.log(
        "=========================================="
    );


    /*
    =======================================================
    VALIDATION
    =======================================================
    */

    if (!orderId) {

        throw new Error(
            "Order ID is required."
        );

    }


    if (!sellerId) {

        throw new Error(
            "Seller ID is required."
        );

    }


    const normalizedCode =
        validateCodeFormat(
            code
        );


    /*
    =======================================================
    ORDER REFERENCE
    =======================================================
    */

    const orderRef =
        db
            .collection(
                COLLECTIONS.ORDERS
            )
            .doc(orderId);


    /*
    =======================================================
    WE FIRST READ THE ORDER
    =======================================================
    */

    const orderSnap =
        await orderRef.get();


    if (!orderSnap.exists) {

        throw new Error(
            "Marketplace order not found."
        );

    }


    const order =
        orderSnap.data();


    /*
    =======================================================
    VERIFY SELLER
    =======================================================
    */

    if (
        order.sellerId !== sellerId
    ) {

        throw new Error(
            "You are not authorized to complete this order."
        );

    }


    /*
    =======================================================
    ALREADY COMPLETED
    =======================================================
    */

    if (
        order.status ===
        ORDER_STATUS.COMPLETED
    ) {

        return {

            success: true,

            alreadyCompleted: true,

            orderId,

            message:
                "This order has already been completed.",

        };

    }


    /*
    =======================================================
    VERIFY PAYMENT
    =======================================================
    */

    if (
        order.paymentStatus !==
        PAYMENT_STATUS.COMPLETED
    ) {

        throw new Error(
            "This order has not been successfully paid."
        );

    }


    /*
    =======================================================
    VERIFY HELD FUNDS
    =======================================================
    */

    if (
        order.sellerPaymentStatus !==
        SELLER_PAYMENT_STATUS.HELD
    ) {

        throw new Error(
            "Seller funds are not currently held for this order."
        );

    }


    /*
    =======================================================
    VERIFY CODE EXISTS
    =======================================================
    */

    if (
        !order.completionCodeHash
    ) {

        throw new Error(
            "This order does not have a completion code."
        );

    }


    /*
    =======================================================
    CHECK CODE STATUS
    =======================================================
    */

    if (
        order.completionCodeUsed ===
        true
    ) {

        throw new Error(
            "This completion code has already been used."
        );

    }


    if (
        order.completionCodeStatus ===
        "LOCKED"
    ) {

        throw new Error(
            "Completion code verification is locked because of too many failed attempts."
        );

    }


    /*
    =======================================================
    CHECK ATTEMPTS
    =======================================================
    */

    const attempts =
        Number(
            order.completionCodeAttempts ||
            0
        );


    if (
        attempts >=
        MAX_VERIFICATION_ATTEMPTS
    ) {

        await orderRef.update({

            completionCodeStatus:
                "LOCKED",

            updatedAt:
                new Date(),

        });


        throw new Error(
            "Too many incorrect completion code attempts."
        );

    }


    /*
    =======================================================
    HASH SUBMITTED CODE
    =======================================================
    */

    const submittedHash =
        hashCompletionCode(
            normalizedCode
        );


    /*
    =======================================================
    CONSTANT-TIME HASH COMPARISON
    =======================================================
    */

    const storedHash =
        String(
            order.completionCodeHash
        );


    const hashesMatch =
        submittedHash.length ===
            storedHash.length &&
        crypto.timingSafeEqual(
            Buffer.from(
                submittedHash
            ),
            Buffer.from(
                storedHash
            )
        );


    /*
    =======================================================
    WRONG CODE
    =======================================================
    */

    if (!hashesMatch) {

        const newAttempts =
            attempts + 1;


        const updateData = {

            completionCodeAttempts:
                newAttempts,

            updatedAt:
                new Date(),

        };


        if (
            newAttempts >=
            MAX_VERIFICATION_ATTEMPTS
        ) {

            updateData
                .completionCodeStatus =
                "LOCKED";

        }


        await orderRef.update(
            updateData
        );


        throw new Error(
            newAttempts >=
                MAX_VERIFICATION_ATTEMPTS
                ? "Too many incorrect attempts. Completion code verification has been locked."
                : "Incorrect completion code."
        );

    }


    /*
    =======================================================
    CODE IS CORRECT
    =======================================================

    IMPORTANT:

    We now perform the completion + settlement inside
    a controlled process.

    =======================================================
    */

    const now =
        new Date();


    /*
    =======================================================
    MARK CODE USED
    =======================================================
    */

    await orderRef.update({

        completionCodeUsed:
            true,

        completionCodeUsedAt:
            now,

        completionCodeUsedBy:
            sellerId,

        completionCodeStatus:
            "USED",

        completionCodeAttempts:
            attempts + 1,

        status:
            ORDER_STATUS.COMPLETED,

        updatedAt:
            now,

    });


    console.log(
        "✅ Completion code verified."
    );


    /*
    =======================================================
    SETTLE SELLER FUNDS
    =======================================================
    */

    let settlement;


    try {

        settlement =
            await settleMarketplaceOrder({

                orderId,

                sellerId,

                completionCodeVerified:
                    true,

            });

    } catch (settlementError) {

        console.error(
            "❌ Settlement failed after completion verification:",
            settlementError
        );


        /*
        IMPORTANT:

        Payment is still safe because funds remain
        logically held unless settlement succeeds.

        However, the order has already been marked
        completed above.

        We therefore mark settlement as requiring
        processing rather than pretending settlement
        succeeded.
        */

        await orderRef.update({

            settlementStatus:
                "PENDING",

            settlementError:
                settlementError.message,

            updatedAt:
                new Date(),

        });


        throw new Error(
            "Completion verified, but seller settlement is pending. The payment remains protected."
        );

    }


    /*
    =======================================================
    SUCCESS
    =======================================================
    */

    console.log(
        "=========================================="
    );

    console.log(
        "🎉 ORDER COMPLETION SUCCESSFUL"
    );

    console.log(
        "Order:",
        orderId
    );

    console.log(
        "Seller:",
        sellerId
    );

    console.log(
        "Settlement:",
        settlement
    );

    console.log(
        "=========================================="
    );


    return {

        success: true,

        alreadyCompleted:
            false,

        orderId,

        sellerId,

        status:
            ORDER_STATUS.COMPLETED,

        completionCodeVerified:
            true,

        settlement,

        message:
            "Completion code verified successfully and seller settlement processed.",

    };

}


/*
=========================================================
GET COMPLETION STATUS
=========================================================
*/

async function getCompletionStatus(
    orderId
) {

    if (!orderId) {

        throw new Error(
            "Order ID is required."
        );

    }


    const orderSnap =
        await db
            .collection(
                COLLECTIONS.ORDERS
            )
            .doc(orderId)
            .get();


    if (!orderSnap.exists) {

        return null;

    }


    const order =
        orderSnap.data();


    return {

        orderId,

        orderStatus:
            order.status,

        paymentStatus:
            order.paymentStatus,

        completionCodeCreated:
            Boolean(
                order.completionCodeHash
            ),

        completionCodeStatus:
            order.completionCodeStatus ||
            "NOT_CREATED",

        completionCodeUsed:
            order.completionCodeUsed ||
            false,

        attempts:
            Number(
                order.completionCodeAttempts ||
                0
            ),

        completionCodeCreatedAt:
            order.completionCodeCreatedAt ||
            null,

        completionCodeUsedAt:
            order.completionCodeUsedAt ||
            null,

    };

}


/*
=========================================================
EXPORTS
=========================================================
*/

module.exports = {

    generateOrderCompletionCode,

    verifyCompletionCode,

    getCompletionStatus,

};